<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<section class="page-landing">
    <img class="logo" src="<?= $this->basePath() ?>/pub/images/mageos/logo.svg" alt="Mage-OS"/>
    <p class="text-version">
        <?= 'Version' . ' ' . $this->version ?>
    </p>
    <p class="text-welcome">
        Welcome to the Mage-OS Web Installer! Your eCommerce store will be running in no time.
        <br>
        Click 'Install Mage-OS' to start, or read <a href="https://devdocs.mage-os.org/docs/main" target="_blank">Getting Started</a> to learn more.
    </p>
    <button
        type="button"
        class="btn btn-large btn-prime btn-submit"
        ng-click="nextState()"
        >Install Mage-OS</button>
</section>
