<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<script>
    document.title = 'Mage-OS Setup - 401 Unauthorized Access';
</script>
<section class="page-landing">
    <img class="logo" src="<?= $this->basePath() ?>/pub/images/mageos.png" alt="Mage-OS"/>
    <p class="text-welcome">
        Welcome to the Mage-OS Web Installer!
        <br>
        It appears you've already installed Mage-OS, so you will need to do any further site updates from the command line using <pre>composer</pre> and <pre>bin/magento</pre>.
    </p>
</section>
